version:  '3'
services:
  jupyter:
    build: .
    volumes:
      - .:/home/jovyan
      - /home/snake/projects/studytube.nl/backend:/home/jovyan/backend
    user: root
    ports:
      - 8888:8888
    environment:
      - OPENAI_API_KEY
      - USERNAME
      - API_KEY